export const COLOR_SCHEME = [
	[
		'global-color-one-scheme-1',
		'global-color-two-scheme-1',
		'global-color-three-scheme-1',
		'global-color-four-scheme-1',
	],
	[
		'global-color-one-scheme-2',
		'global-color-two-scheme-2',
		'global-color-three-scheme-2',
		'global-color-four-scheme-2',
	],
	[
		'global-color-one-scheme-3',
		'global-color-two-scheme-3',
		'global-color-three-scheme-3',
		'global-color-four-scheme-3',
	],
]
